PROMPTS = {'Mystery / Thriller': [
    'You are the world’s greatest detective. With your near superhuman intellect, you have never failed to solve a case before. One day, you finally meet your match: a criminal so unbelievably stupid that you cannot possibly comprehend and predict what he’s going to do next. (Reedsy)',
    'The first day you opened your own office as a private investigator, you didn’t expect it to be busy. You were wrong. (Reedsy)',
    'The detective didn’t realize they were being foiled by a competing detective. (Reedsy)',
    'As you’re paying for your groceries, you mention to the clerk, “There’s a mess in aisle 16.” They give you a puzzled look and reply, “There is no aisle 16.” (Reedsy)',
    'You’re shaking hands with a stranger at a networking event when you ask for their name. “I have no name,” they reply. (Reedsy)',
    '20 years after your daughter was abducted, a detective finds you to reopen the case. The detective turns out to be your daughter. (Reedsy)',
    'You hire two private investigators to investigate each other. One month later both come to you to present their findings. (Reedsy)',
    'You are legally allowed to commit murder once, but you must fill out the proper paperwork and your proposed victim will be notified of your intentions. (Reedsy)',
    'You’re a serial killer who murders anyone you see hitchhiking up your mountain. One day, you pick up a hitchhiker who kills anyone who picks them up.',
    '“… and that’s why dividing by three is illegal.” (Reedsy)',
    'Looking through old family photos, multiple generations back, you notice there is a cat in almost every group photo. The same cat – color, pattern, one docked ear – that is currently purring on your lap. (Reedsy)',
    'You were the oldest person still living in the town and you remembered things no one else did. (Reedsy)',
    'They say a picture is worth a thousand words but you knew the one you’d just taken was worth a million. (Reedsy)',
    'Write a short dark comedy in which a long-unsolved mystery is finally cracked. (Reedsy)',
    'As you’re browsing through a rack of sweaters, someone approaches you and says, “I need you to listen to me very carefully.” (Reedsy)',
    'A loved one confides in you, but the secret could damage someone else you care about. What do you do? (Reedsy)',
    'Guard this with your life. (Reedsy)',
    'You walk into your job and find a secret, coded note pinned to your desk. What do you do next? (Reedsy)',
    'You wake up in a jail cell, crusted blood covering your hands. You have no idea how you got there. The cell door clangs open, and an officer walks you to interrogation room where two detectives wait to question you. (Reedsy)',
    'You find a hand-written note on your windshield that says, “Drive west for 100 miles.” (Reedsy)',
    'The morning after a blizzard you make your way outside and slowly start to realize everyone has disappeared. (Reedsy)',
    'She has been walking for hours. Her feet are starting to bleed. But she can’t stop moving… she can’t let him find her again. (Reedsy)',
    'You’ve lived an average life up until today, your 20th birthday. You just found out that your dad is the runaway son of a doting criminal warlord, and your mom is the daughter of an equally doting secret agent. Both family businesses are looking to make you the next heir. (Reedsy)',
    'Ever since childhood, a dark figure no one else can see has been following you around, whispering in your ear. Today you see it lying a few feet away, screaming and asking you to run. (Reedsy)',
    'A terrorist group has been infiltrated by so many agencies that it is now run by spies, unbeknownst to the spies themselves. This fact becomes apparent to an actual extremist who joins their ranks. (Reedsy)',
    'You work for the CIA who send you undercover in the FBI, who send you undercover in M16, who send you undercover in the CIA, who are very confused that you are back after only two weeks. (Reedsy)',
    'You’re at a huge store scouting out Black Friday deals. You start to notice that all the security cameras in the store seem to be following your each and every move. (Reedsy)',
    'You’re sitting by a window watching the flakes slowly and silently fall. Suddenly, you see something outside that snaps you out of your reverie. (Reedsy)',
    'Your fingers tensed around the object in your pocket, ready to pull it out at a moment’s notice. (Reedsy)',
    'Write a short story where the protagonist has a doppelganger. (Reedsy)',
    'You can solve murders simply by stepping foot at the crime scene. Problem is, no one believes you.',
    'Local gravestones begin disappearing.',
    'The FBI begs you to come back to work on a special case. Your former partner has turned and is now wanted for the murders of three co-workers.',
    'The day of your wedding, you wake up to find every person in your wedding party has been brutally murdered.',
    'Three words: Long lost brother.',
    'Your best friend tells you that she feels like someone’s been watching her. The next day she goes missing.',
    'You aunt passes away, leaving you $500,000 in her will under the condition that you resume care for your hundred-year-old home.',
    'You begin to realize that your reflection is no longer appearing in mirrors.',
    'An international spy group recruits you to be their latest member.',
    'The protagonist of your story discovers that there is a person who looks exactly like him.',
    'You wake up to discover a completely different, unknown face staring back at you from the mirror.',
    'Someone puts a large black box on your doorstep. A note on the front reads, “Caution: may bite.”',
    'Your parents tell you that they actually don’t know whose child you are.',
    'You get a text message from an unknown number saying, “Meet me outside. Now.”',
    'You stumble upon a strange house you’ve never seen before on your morning run.',
    'One day at work, you look across the street to see a hooded figure in a black coat pointing directly at you. What do they want?',
    'One day the national news channel shuts off. And the next day after that, too.',
    'You hear news of your next-door neighbor vanishing without a trace.',
    'A stranger sits down next to you on a train and gets up, leaving a package behind. Do you investigate the package?',
    'You find strange, muddy footprints leading up to your front door.'],
           'Romance': ['An avalanche strands two mortal enemies together… and they start to fall in love.',
                       'They might have aged 50 years, but when they held you, those hands felt exactly like they did the first time. (Reedsy)',
                       'You’ve been bumping into the same stranger for months. Finally, you decide to say hello. (Reedsy)',
                       'A dog lover and cat lover fall in love… and must find a way to get their animals to fall in love, too.',
                       'You never would have guessed that in 48 hours you’d be married. (Reedsy)',
                       'You and your partner finally have the most romantic vacation planned. Problem is, your in-laws decided to tag along at the last minute.',
                       'You have the ability to make anyone fall in love with you. You’ve just fallen in love for the first time. Do you use your power? (Reedsy)',
                       'Well, that was a New Year’s Eve kiss you won’t forget any time soon. (Reedsy)',
                       'Valentine’s Day at a retirement home. (Reedsy)',
                       'Two mortal enemies fall in love when they’re trapped in an elevator together and begin to see the other person’s perspective. (Reedsy)',
                       'Two characters who are perfect for one another are foiled by bad timing. (Reedsy)',
                       'They lived in a world where PDA is forbidden. One day, they slipped up and held hands on the street. (Reedsy)',
                       'The lives of two people are changed forever when they coincidentally meet and engage in a weekend-long affair. (Reedsy)',
                       'Someone with anxiety falls in love with someone extremely adventurous. (Reedsy)',
                       'It wasn’t love at first sight. But now you were starting to see them in a new light… (Reedsy)',
                       'A fortune teller falls in love with their client who has their palm read every month. (Reedsy)',
                       'In the future, romantic attraction is literal: each person is fitted with an electromagnetic bracelet which, they claim, will pull you to your soulmate. It’s the day they turn the magnets on, and you’re waiting. (Reedsy)',
                       'Write a romantic comedy. Difficulty: both lovers are emotionally mature and have excellent communication skills. (Reedsy)',
                       'You meet your doppelganger of the opposite sex and find you are strangely attracted to each other. (Reedsy)',
                       'Cupid offers to shoot an arrow into the person you love. He warns you that if the person already has a pre-existing affection towards you, it will disappear when the arrow strikes. (Reedsy)',
                       'Every day, you return to your apartment and say, “Honey, I’m home. Oh wait, that’s right… I live alone.” But then one day, a voice replies, “I picked up some pizza.” (Reedsy)',
                       'At your friend’s urging, you begrudgingly attend a Valentine’s Day speed dating event. (Reedsy)',
                       'You and your best friends decide to try a new dating app for the first time.',
                       'You realize that you’ve fallen out of love with your new wife while you’re on your honeymoon.',
                       'After you move to a new city, you fall in love with your realtor while buying a new house.',
                       'You’re a mail order bride arriving at her new home for the first time.',
                       'You fall in love with every person you make eye contact with.',
                       'The love of your life is your brother’s nemesis.',
                       'You are a popular book heroine’s love interest. You now have 60 seconds to convince them that saving the city is more important than saving you. (@writing.prompt.s)',
                       'A Republican presidential candidate and Democratic presidential candidate fall in love.',
                       'A daughter tries to set her widowed father up on an online dating app – without him knowing.',
                       'A chef decides to embark on an international culinary tour for inspiration and falls in love with their tour guide.',
                       'Two widowed people meet at a community garden.',
                       'A cutthroat business woman swore she’d never find love until her best friend sets her up on a blind date.',
                       'Desperate for cash, a med student signs up to be a nude model for a retired women’s art club.',
                       'An alien falls in love with a forbidden human.',
                       'She’s a burgeoning lingerie model who needs her cute neighbor to take portfolio shots of her.',
                       'After their catamaran crashes, a husband and wife on their anniversary trip are left marooned on an island in the tropics.',
                       'A parole officer falls in love with his parolee.',
                       'Two strangers on an online chat room hit it off. Turns out they’re childhood sweethearts.',
                       'You get to make one wish to create your dream romantic partner. What is it?',
                       'A college professor and their teaching assistant hit it off a little too well.',
                       'Write a love story set at the zoo.', 'You and a hot stranger get trapped in an elevator.',
                       'Your husband accidentally sends you a text meant for his mistress.',
                       'After joining an adult swim league, you realize that your coach is irresistibly cute.',
                       'A divorced former couple find each other on the same flight to Paris… Sitting next to each other.',
                       'A stranger texts the wrong number, and accidentally sends you a declaration of love. The message is so sweet and heartfelt that you know you can’t let it go.',
                       'You got ditched at the last minute before prom – who will your date be?',
                       'Left at the altar, you decide to seek revenge on your ex.'], 'Science Fiction': [
        'Creation myth! Write from the perspective of a crazy scientist in the year 28,000 who, determined to discover how the universe began, rigs up a malfunctioning time machine, goes to the “beginning” of the universe, and ends up being the reason for the Big Bang. (Logic? Causal effect? Pfft. Hush, it’s time-travel, and that was never logical.) (The Write Practice)',
        'Steampunk! Write a story from the perspective of a hot air balloon operator who caters to folks who like a little thrill… which means she spends half her time in the air shooting down pterodactyls before the paying customers get TOO scared. (The Write Practice)',
        'In the nineteenth century, there’s a thriving trade in stolen archeological artifacts. Write a story from the perspective of an annoyed, minimum-wage employee whose job is traveling back in time to obtain otherwise unobtainable artifacts, then has to bring them back to the present (the 1800s, that is) and artificially age them before they will sell. (The Write Practice)',
        'It’s the year 5000. Our planet was wrecked in the great Crisis of 3500, and remaining human civilization survives only in a half dozen giant domed cities. There are two unbreakable rules: strict adherence to Life Quality (recycling doesn’t even begin to cover these laws), and a complete ban on reproduction (only the “worthy” are permitted to create new humans). Write from the perspective of a young woman who just discovered she’s been chosen to reproduce—but she has no interest in being a mother. (The Write Practice)',
        'In the future, neural implants translate music into physical pleasure, and earphones (“jacking in”) are now the drug of choice. Write either from the perspective of a music addict, OR the Sonforce agent (sonance + enforcer) who has the job of cracking down. (The Write Practice)',
        'Ten years from now, scientists figure out how to stop human aging and extend life indefinitely—but every time someone qualifies for that boost, someone else has to die to keep the surplus population in check. Oh, it’s all very humane; one’s descendants get a huge paycheck. Write from the perspective of someone who just got a letter in the mail saying they’re the one who has to die. (The Write Practice)',
        'So yeah, ancient Egypt really was “all that” after all, and the pyramids turn out to be fully functional spaceships (the limestone was to preserve the electronics hidden inside). Write from the perspective of the tourist who accidentally turns one on. (The Write Practice)',
        'Time travel works, but only once in a person’s life. Write from the perspective of someone who chooses to go back in time, knowing they can never return. Where do they go and why? (The Write Practice)',
        'A high schooler from fifteen hundred years in our future is assigned a one-page writing project on a twenty-first century person’s life based entirely on TV commercials. Write the beginning of the essay. (The Write Practice)',
        'House cats are aliens who have succeeded in their plan to rule the world. Discuss.',
        'Take anything we find normal today (shopping malls, infomercials, products to remove facial hair, etc.) and write a story from the perspective of an archeologist five thousand years in the future who just unearthed this stuff, has NO idea what any of it was for, and has to give a speech in an hour explaining the historical/religious/sociological significance. (The Write Practice)',
        'An alien planet starts receiving bizarre audio transmissions from another world (spoiler: they’re from Earth). What does it mean? Are they under attack? Some think so…until classic rock ‘n’ roll hits the airwaves, and these aliens discover dancing. Write from the perspective of the teenaged alien who first figures it out. (The Write Practice)',
        'Ever read about the world’s loneliest whale? Write a story in which he’s actually the survivor of an aquatic alien species which crashed here eons ago, and he’s trying very hard to learn the “local” whale language so he can fit in. Write from his perspective the first time he makes contact. (The Write Practice)',
        'A rogue planet with strange properties collides with our sun, and after it’s all over, worldwide temperature falls forty degrees. Write from the perspective of a someone trying to keep his tropical fruit trees alive. (The Write Practice)',
        'Aliens who only communicate with sign language invade. To avoid war, our governments must engage a vastly marginalized portion of the human population: the hearing-impaired. (The Write Practice)',
        'Your penpal lives on the opposite side of the universe.', 'Describe your perfect utopian world.',
        'What do you think happens when the grid goes down?',
        'In the future, we no longer require water, air, or food. We are a super efficient team of robots.',
        'The year is 2200. What does the world look like to you?',
        'Everyone on earth begins to experience universal amnesia.',
        'What if the universe as we know it is actually someone’s imagination? (Screencraft)',
        'What if the sun began to die? (Screencraft)',
        'What if your stepfather or stepmother is actually your future self? (Screencraft)',
        'What if the past and present timelines began to merge? (Screencraft)',
        'What if the world we live in is actually a computer simulation? (Screencraft)',
        'What if a nuclear submarine was ordered to launch their nuclear arsenal onto the world? (Screencraft)',
        'Nasa engineers monitor the curiosity rover’s actions. All seems normal until the robot suddenly changes its course. The scientists attempt to correct it over and over until they suddenly receive a transmission from the rover: “Will Save Oppy” (@writing.prompt.s)',
        'You’re a 15-year-old in the middle of a zombie apocalypse. However, a cure has been found that not only rids the infected person of the virus before they turn but prevents it altogether. Only one problem… Your parents are anti-vaxxers. (@writing.prompt.s)',
        'In an alternate universe where global warming has ruined the planet, you’ve spent your entire life living in an airplane on autopilot.',
        'Your whole family has fought in the space military, but you’ve decided to no longer take part in it.',
        'Walking through the woods one day, you come across a small animal that has the ability to instantaneously clone itself.',
        'You are one of the mechanics on the first ever self-flying airplane.',
        'All plant life on the planet is wiped out, except for in Florida.', 'Technology becomes illegal.',
        'You are in charge of a secretive government agency that aligns people’s fates. Their livelihood is entirely up to you and what you want to do with it.',
        'It turns out humans have been the aliens all along.',
        'Human beings begin to find themselves growing extra limbs as global warming amps up.',
        'A rare form of cancer is the newest superbug. With a team of scientists, you all must find a cure before the population is wiped out.',
        'You are the first person able to breathe in outer space.',
        'The world is dying. In order to save it, you’ve been commanded to sacrifice yourself to an invading alien group.',
        'What team do you gather to fight the largest alien and terrorist threat on Earth?',
        'You have to power to build one separate planet. How do you build it? Who gets to live there?',
        'Everyone in the world has the ability to read thoughts. Except for one person.',
        'After people die, their spirits can be brought back from death but at the cost of one random human life. Is it worth it?',
        'You are chosen to go on the first ever recreational space journey.', 'Gravity no longer exists.',
        'Every day, you get one hour to revisit any moment from your life. What do you pick?', 'Your wife is a droid.',
        'You wake up one morning to find out that you get to move to any planet of your choosing.'],
           'Fantasy / Paranormal': [
               'A group of scientists on a submarine are alarmed when they spot what looks like a functioning lighthouse at the bottom of the ocean. (Reedsy)',
               'They found out about us. They’re coming. They were the words the kingdom had feared hearing for thousands of years. (Reedsy)',
               'I wish I could skip next week, you think as you get into bed that night. In the morning, you wake up 100 years in the future. (Reesy)',
               'You wake up 10 years younger. What do you do? (Reedsy)',
               'It’s 1AM at night. But the sun is out. (Reedsy)',
               'A new candy had been invented that allowed the person who ate it to relive any memory they wanted. There was a lineup outside the shop. (Reedsy)',
               'Silence is now literally golden. For every day of total silence a person completes, they receive a piece of gold. (Reedsy)',
               'As a joke, you put on a tinfoil hat. Suddenly your mind goes completely silent. (Reedsy)',
               'Write a story that includes a character hearing their fate by a fortune teller. (Reedsy)',
               'You were on your way to see a doctor who promised to know the secret to making yourself fall out of love with someone. (Reedsy)',
               'You find a polaroid camera that seems to predict the future: its pictures show what will happen exactly 5 minutes from the moment you take them. (Reedsy)',
               'You can buy a pill that lets you decide exactly what you will dream about while you sleep. (Reedsy)',
               'You start realizing that at least one aspect of every dream you have comes true the next day. (Reedsy)',
               '10 cm of snow had fallen overnight, just as the weatherman predicted. The only thing is… the snow isn’t white. (Reedsy)',
               'You and your adventurous crew on a quest for the old King’s hidden gold. Just one problem – so is the rest of your village.',
               'Dream up your own, one-of-a-kind mythical race.',
               'Spend some time working on world building. How can you create a believable fantasy world that readers can picture clearly? What types of characters does your world include?',
               'You were born to be a villain, but you find yourself leaning more and more towards the good as you get older.',
               'You’re the one human who is capable of seeing ghosts. It’s up to you to save them from being removed from the human world for good.',
               'No, there’s absolutely no way that ghosts are real. Sure, you just saw a mysterious fuzzy figure you appear before you in your house, but that had to be your imagination… right?',
               'You and your ghost best friend are an infamous crime-solving team.',
               'You have the power to transform into whatever mystical creature you choose.',
               'You and your family are on a hike when you stumble upon a group of witches in the forest, in the midst of casting spells.',
               'You are the last person on Earth, and you are able to make one wish. What do you wish for?',
               'A lord takes a fancy to a peasant girl and kidnaps her for his own. Little does he know that she’s a trained assassin who has been preparing to take his life for years. (@writing.prompt.s)',
               'The stars have been watching you your whole life, as you laughed and cried, loved and suffered. Today, you’re finally going to do something that none of them can bear to watch. They blink out, the whole night sky turning dark, just as you’re about to do it. (@writing.prompt.s)',
               'You’re an immortal who lives at a beach resort. You have many summer flings with mortals on getaways. One day you see someone you had a hot romantic night with 50 years ago. They look exactly the same. (@writing.prompt.s)',
               'The cocky main character of a popular book is sent to the real world. He is shocked to find that the fans of his book not only like the villain more but favor his side kick over him. (@writing.prompt.s)',
               'A woman has been dating guy after guy, but it never seems to work out. She’s unaware that she’s actually been dating the same guy over and over; a shapeshifter who’s fallen for her and is certain he’s going to get it right this time.  (@writing.prompt.s)',
               'You are the king. After your daughter was kidnapped by a dragon, you offered the standard reward to whoever rescued her. You weren’t expecting a different dragon to rescue her. (@writing.prompt.s)',
               'Satan puts you in charge of Hell.', 'Regular person by day, a shape shifter by night.',
               'An underwater society decides to overtake the world.',
               'You wake up to find yourself a member of King Arthur’s Round Table.',
               'You’re selected to take part in a secretive, underground magic university… but you have to kill someone to go.',
               'You come into possession of a ring that can change the weather to whatever you decide.',
               'A magical toad begins talking to you, but you’re the only person who can hear him.',
               'A man and his wife own the largest potion store in town. Little do the townspeople know, but they’re all being slowly poisoned by the potions.',
               'You are kidnapped by a knight who demands your assistance in sleighing the city’s most dangerous dragon.',
               'Your favorite fairy tale is now set in 2019.', 'Fairies are tired of being used for free labor.',
               'You have the power to read the lost language, making you the only person to decipher the scroll.',
               'You must save your kingdom from ruin by learning how to breathe fire.', 'The ocean becomes the sky.',
               'On her deathbed, your grandmother tells you that there’s a hidden treasure buried in her backyard. The family has been trying to locate it for decades. It’s up to you to finally find it.',
               'You wake up and find out that you’re the only living person left on the planet.',
               'A magical world exists underground. To get there, you’ll need to start digging.',
               'You are gifted with the strongest, most elusive sword in the kingdom, but if you use it you will never be able to speak again.',
               'Your pet dragon transforms into a person.',
               'A mysterious creature speaks to you in your dreams and tells you that when you awake, you will have the ability to see into another realm.'],
           'General Fiction': ['You get one chance to talk to any person in the world. Who do you choose?',
                               'You’re put in charge of taking care of your elderly grandmother towards the end of her life.',
                               'Imagine what would happen if every person in the world woke up in a good mood every day.',
                               'You’re allergic to oxygen.',
                               'Tell the story of seeing the ocean for the first time. Or the last.',
                               'You go on a road trip to visit your late father’s grave.',
                               'You’re the judge of the annual pie contest in your hometown but, unbeknownst to you, one of the pies is poisoned.',
                               'The worst thing that you could imagine happening happens.',
                               'You own a tiny mom and pops-type store that you run with your family.',
                               'After years on the job search, you’ve finally gotten your dream job – but it changes you for the worst.',
                               'Tell a story using only one sense – seeing, hearing, tasting, smelling, or touching.',
                               'Write from the perspective of your worst enemy.', 'Tell a story through song.',
                               'Imagine what it would be like to be a pop star.',
                               'Tell the story of the first time that you learned to do something really well.',
                               'What would a world be like with no poverty? What would change? What would stay the same?',
                               'Imagine how you would help solve the greatest challenges that the world faces. What would your plan be?',
                               'Tell a story from your favorite era.', 'Write your own obituary.',
                               'Tell the story of what you would do if you won the lottery.',
                               'Tell a story through text messages.',
                               'Imagine telling the story of a professional hypnotizer. (Reedsy)',
                               'Using only dialogue, write a short story about a first date, a reunion between old friends, an argument that gets heated, an adult explaining something to a child, or the reveal of a long-hidden secret. (Reedsy)',
                               'Write a story about someone who would be described, above all else, as honest. Or kind. Or intelligent. (Reedsy)',
                               'Write a short story in which the main “character” is the setting: for example, a house. (Reedsy)',
                               'Write a short story with an unreliable narrator that readers can never quite trust. (Reedsy)',
                               'Write a story about a character waking up to the best news of their life. (Reedsy)',
                               'Write a story about a character waking up to something absurd. (Reedsy)',
                               'When people are born, they are assigned a soulmate. They have a song in their head that only them and their soulmate know. How do you find your soulmate? (@writing.prompt.s)',
                               'Death has been flirting with you for a long time, but they’ve become a bit annoying. After another attempting to hang out with you again, you jokingly tell them, “If I was the last person on Earth, I’d maybe give you a chance.” Death believes you and will double their efforts.',
                               'You live in a world with no stress and fear.',
                               'What’s the greatest advice you’ve ever been given? What if you lived solely according to it?',
                               'Write a scene detailing your greatest fear. Now imagine that has come true for your character.',
                               'As an 80-year-old, you decide to finally learn how to swim so you can participate in a triathlon.',
                               'The dark family secret that’s always been hidden comes to light.',
                               'You have the power to create, and star in, your own reality show. What does it look like?',
                               'A famous shoe designer asks you to quit your job and be his latest model.',
                               'You’ve just returned home from war only to find your family missing without a trace.',
                               'Your dream is to open a restaurant and be a top chef, but how can you do that when you were born without taste buds?',
                               'Tell the story of one woman on the mission to find her lost biological daughter.',
                               'Describe the life of a struggling author attempting to make it “big.”',
                               'Use five points of view to describe one situation.',
                               'By way of a lottery system, the king chooses you to be his queen.',
                               'Think about what you are most proud of. Follow the story of how you got to that point.',
                               'Imagine what would happen if you woke up one morning unable to see, speak, or hear.',
                               'Detail the life of the person who inspires you the most.',
                               'What was the strangest thing you’ve ever seen in public?',
                               'You have to get to the bottom of your family’s deepest secret.',
                               'Coffee is illegal and you have to single handedly smuggle it into the country.',
                               'You’re chasing your dream of being the first person to fly.'],
           'Religion / Spirituality': ['What are your thoughts on love languages?',
                                       'Some religions believe that human beings could never truly represent a higher power in art. Do you agree with this? What is an example of art or words that you feel represent the higher power?',
                                       'What is your most taboo religious belief?',
                                       'Describe a particularly spiritual moment in your life. What were you doing? Were you by yourself or with someone else?',
                                       'Some religions believe that animals and plants have souls. Do you agree with this? Why or why not?',
                                       'What would reincarnation look like to you?', 'Do you believe in reincarnation?',
                                       'Emanuel Swedenborg believed that there was a soulmate for every person, and that you couldn’t get into heaven until your soul mate had also passed away. Do you believe in the concept of soul mates?',
                                       'How have you experienced the divine through love?',
                                       'William Blake, famous British poet, thought that to love was to be in tune with the divine. Do you think this is true? How have you experienced divine love?',
                                       'Have you ever had an out of body experience?',
                                       'What form do you think the afterlife will take, if you believe that it exists?',
                                       'Have you ever felt like you’ve experienced a glimpse into the afterlife?',
                                       'When was a specific moment where you felt a “divine presence” in your life?',
                                       'What are your personal ten commandments?',
                                       'A secular Jew and a devout Muslim debate food and faith on a train from Quebec to Montreal.',
                                       'You record a video that seemingly shows a woman walking on water at a small rural pond. The video goes viral as proof that Jesus has returned, and Christians begin to wonder if Christ was the Daughter, not the Son, of God.',
                                       'An opiate addict going through severe withdrawal symptoms has a conversation with the Buddha – what did they talk about, and was it the result of a fever dream, or a spiritual awakening?',
                                       'God needs a vacation from heaven, so he comes to earth to experience life as a dog. He is captured by animal control and is impounded, and you adopt god-the-dog after a tragedy that makes you question your faith.',
                                       'The Southern Baptist Convention elects its first woman president, though she is subsequently removed from the position due to an obscure rule. In protest, every woman leaves the Southern Baptist denomination to form an independent, women-only sect of Baptists.',
                                       'If you could talk to God, what would you want to say?',
                                       'How would you advise someone to strengthen their faith?',
                                       'What do you hope your religious or spirituality path to look like as you age?',
                                       'Describe what your childhood views in spirituality or religion were.',
                                       'Put yourself in the shoes of someone who has completely opposite spiritual or religious views from you. Why do they think a certain way?',
                                       'What makes you non religious?', 'What makes you religious?',
                                       'How does one know what is innately good?',
                                       'What is the difference in good versus evil? How do you know?',
                                       'Think about what morality means to you.',
                                       'What happens when a priest decides he doesn’t want to be a priest anymore?',
                                       'Write a religious comedy.', 'Write a poem about your religious path in life.',
                                       'Describe what a church means to you. Have you had positive or negative experiences in a church?',
                                       'What makes you a religious or spiritual person?',
                                       'You have the power to make every single person in the world ether religious or nonreligious. What do you do? What changes about the world?',
                                       'What would your ideal world look like?', 'What does karma mean to you?',
                                       'You live in a world where no Gods exist.',
                                       'Detail your favorite story in the holy text of your choosing.',
                                       'Describe your idea of heaven.',
                                       'Who is one religious figure you would like to have dinner with? What do you talk to them about?',
                                       'What is the greatest wisdom that you would like to impart on the world?',
                                       'What helps you meditate?',
                                       'Explore what it means to be religious versus spiritual.',
                                       'You must live every single day according to a holy text of your choice. What happens?',
                                       'You get to build a religion of your own. What do you make it into?',
                                       'What do you find to be most beautiful in the world?',
                                       'God speaks directly to you – what does He say?',
                                       'What makes you believe in God?'], 'Travel / Adventure': [
        'In a high-stakes game of poker in the French Quarter, you wagered your soul to a voodoo doctor on a pretty bad hand. The only way to null the bet is to find a woman in Port-au-Prince, Haiti who has an item – the only  item – the man is willing to trade for.',
        'You have to make it from Cairo to Alexandria (Egypt). You have no money. Your only mode of transport is a temperamental camel.',
        'While en route to visit your college roommate in Kyoto, Japan you meet a stranger at Tan Son Nhat International Airport who needs your help finding a prophetic monk hiding from persecution in Saigon.',
        'You are a sales representative for a roulette table manufacturer. While visiting the Harrah’s Cherokee Casino for work, you decide to discard all your possessions, cash out your minimal savings, and hike the Mountains-to-Sea trail from Clingmans Dome to the Ocracoke Lighthouse.',
        'A three day visit to Budapest becomes a maritime adventure down the Danube River to the Black Sea.',
        'Set the scene for a gorgeous castle that you have never traveled to.',
        'Set the scene for a beautiful beach that you have never traveled to.',
        'If you had to move to a foreign country tomorrow, what five items would you pack with you?',
        'Picture yourself on a foreign vacation with a person of your choosing. What do you do?',
        'What is your happiest story from traveling?', 'What is your greatest horror story from traveling?',
        'You get to go to any museum in the world. Which one do you choose?',
        'What is the most beautiful image that you have ever seen while traveling?',
        'Describe a time when you have been excited to explore a new place.',
        'Imagine that you are a successful chef in a foreign city.',
        'Describe the foreign foods that you most want to try.',
        'What cultural norms are you most interested in exploring from foreign countries?',
        'What do you think is most misunderstood about the culture of your home country?',
        'What is the most unusual place you’d like to travel?', 'Explore what your travels in Africa have been like.',
        'Explore what your travels in North America have been like.',
        'Explore what your travels in South America have been like.',
        'Explore what your travels in Europe have been like.', 'Explore what your travels in Asia have been like.',
        'You have the opportunity to move anywhere in the world. Where do you choose?',
        'What stories would you most like to share about the town that you’re from?',
        'What is frightening about traveling? Explore that feeling.',
        'What is it that you love about traveling? Explore that feeling.',
        'Describe what it’s like to travel with a crippling fear of airplanes.',
        'A journey to a new location is disrupted by natural disaster.',
        'Describe what it’s like to sit in rush hour traffic in one of the busiest cities in the world.',
        'What do you say to your family in a postcard from a new location?',
        'Imagine if you had never left your home in your entire life and then were forced to go outside and never come back to your house.',
        'Describe a 100-day walking journey around your state.',
        'You and your partner are kidnapped on your honeymoon.',
        'If you could have any travel-related job in the world, what would it be?',
        'Rate your top five favorite places in the world. What do you like about each place? What do you dislike?',
        'Go back in time to the era of your choosing and describe how you live.', 'What about traveling excites you?',
        'You are forced to leave your home and move to a remote foreign country. What do you pack with you?',
        'You are asked to review a luxury hotel on the beach.',
        'You and your best friends go on a road trip across America, with no budget and for however long you want.',
        'A country of your choosing fuses with North America.',
        'Tell the story of the worst traveling experience of your life.', 'What’s your dream vacation?',
        'What country have you always dreamt of traveling to?',
        'Your favorite chef asks you to join them on a culinary tour of the world.',
        'You get lost in a foreign city with no cell phone and no money. What do you do?',
        'What culture interests you the most?', 'Write about your favorite vacation.'], 'Horror': [
        'During a renovation of your home, you and your spouse find human remains underneath your back porch – a crime that you are now being charged with.',
        'You discover, much too late, that your downstairs neighbor is a cannibal.',
        'On your way to work, you notice that no one is driving on roads. The busy rush hour traffic is nonexistent, and there are no people walking around, either. It’s just you. What’s going on?',
        'You’re on vacation in a new city for the first time. As you walk down a busy boulevard, you suddenly look up to realize you have no idea where you are or how you got there. Come to think of it, you don’t even know who you are.',
        'As you’re settling in to bed for the night, you hear an unusual scratching sound at your bedroom window.',
        'You stumble across a website that contains clues to some very disturbing crimes.',
        'Your dog has been acting very strangely recently. Some would say… almost human.',
        'Several weeks after buying your dream house, you start getting strange letters delivered in the mail warning you to move out.',
        'You awake in a dark, small box and can hear strange noises outside.',
        'Moments after taking off for a flight, the entire plane begins to shake dramatically. The pilot comes on the speaker and says, “This is very bad.”',
        'You wake up in the middle of the night to see a dark figure crawling across your floor.',
        'A little boy’s lost in the woods, but at least his faithful dog is with him. As they look for the way out, the dog defends his master against terrifying monsters and animals. Finally, the boy arrives safely on the other side, beautiful green field, no more fog or night. Then the dog goes home . . . where his owner, the little boy, has died. The good doggy guarded him all the way to his final rest. (The Write Practice)',
        'On Halloween night, lovers get to come back and spend the evening together one more time. One couple from the Roaring Twenties decides to come back from the grave to help their extreme nerd great-grandchild or the kid will never get married. (The Practice)',
        'Aliens have just landed on Earth—and boy, did they pick a weird day to come. How do they respond to Halloween, supernatural or otherwise? Do they decide this place is just too bizarre and get the heck out . . . or do they stick around and join in the fun? (The Write Practice)',
        'A young woman goes to her grandmother’s house for tea on Halloween night. They have a wonderful time together, sharing stories, joy, and the best times of family. The next day, the woman learns her grandmother has been dead for a week and no one could get ahold of her to tell her. (The Write Practice)',
        'A bad-tempered businessman is driving home after a long day of work. He thinks he sees his kids trick-or-treating and stops to pick them up—but those aren’t costumes. (The Write Practice)',
        'You’ve put that doll in the cabinet, in the closet, in the attic, but no matter where you tuck it, it always shows back up on the sofa. On Halloween night, you come out to find it watching you… (The Write Practice)',
        'It’s late at night, and you hear footsteps in the cellar—but you’re definitely home alone… or so you thought. (The Write Practice)',
        'What appears to be a ghost approaches your car while you’re waiting at a stoplight.',
        'A man murders his wife while sleepwalking.',
        'A man suffers from sleep paralysis at the worst possible time. (Screencraft)',
        'Suburbia is actually purgatory. (Screencraft)',
        'Deceased soldiers return to their Civil War-era homes. (Screencraft)',
        'A man wakes up with no mouth. (Screencraft)',
        'A boy’s stepfather is actually a murderous werewolf. (Screencraft)',
        'A bartender serves last call to the only remaining patron who is the Devil himself. (Screencraft)',
        'A treasure hunter finds a tomb buried beneath the dirt. (Screencraft)',
        'A woman afraid of clowns is forced to work in a travelling circus. (Screencraft)',
        'You wake up bound to an electric chair, moments before your imminent death.',
        'The reason no one has ever seen the real Santa Claus is because everyone who sees him dies. You just saw him and now you need to survive. (@writing.prompt.s)',
        'For the last few days, you’ve been getting ominous messages written in blood on your bathroom mirror. Turns out, they’re from an awkward ghost with a serious crush on you. (@writing.prompt.s)',
        'Your dog won’t stop barking at a sunken spot in your living room floor.',
        'You’re in the middle of a bank robbery – hiding in the bathroom.',
        'While working at a clothing store, you’re closing up the shop for the night when you see five men walk in through the front door and lock it behind them.',
        'The cruise ship is haunted.', 'A strange man living down the street begins leaving presents at your doorstep.',
        'One day, while you’re in the shower, you hear your front door open and close. “Hey, roomie, I’m home!” Someone shouts. You don’t have a roommate.',
        'You’re driving at night when you can’t help but shake the feeling that there’s a person in your back seat.',
        'The old cuckoo clock at your grandmother’s home is haunted.',
        'A chilling voice appears in your head. It won’t go away. One day, it tells you that you have to run.',
        'You wake up in a strange room, tied to a chair, with a single knife on the floor pointed at you.',
        'Whatever building you enter, you can see all of the people who died there.',
        'A polar vortex freezes the entire planet.',
        'While watching the evening news, the anchor looks directly at the camera and begins screaming before the camera cuts to black.',
        'Strange murmuring sounds being to come from the door that leads to your basement.',
        'Animals take over the world.',
        'Someone knocks at your door. You open it to find your deceased grandfather who has come back from the dead to pay you a visit. What does he want?',
        'A random number texts you saying, “Don’t forget, you’re next.”',
        'A masked stranger appears at your front door with a knife.',
        'You wake up to a world in which all prisons are shut down, releasing dangerous prisoners into your neighborhood.'],
           'Children’s': [
               'Tell the story of the tooth fairy… Imagine that she just started her job and has to be trained.',
               'Bruce the German Shepherd loves to run through the woods with his human. When he and his human get separated from one another, Bruce has to learn from his forest friends how to get back home.',
               'A dragon wants to be loved and befriended, but every time he farts, fire erupts from his rear end.',
               'A giraffe and an ostrich live together in a zoo, where they bond over similar neck characteristics and learn how to play one another’s games.',
               'Bobby the Bunny wants to make friends with a fox pup who recently lost its family.',
               'Write a book advising children on how to be a kind sibling.',
               'Write a book advising children on how to be a good friend.',
               'Write a book advising children on how to overcome adversity.',
               'Picture a world where everything is upside down! What’s life like for you?',
               'You decide to run away from home – what are some of the challenges that you face?',
               'You’re in charge of babysitting your little sibling for the first time.',
               'Take a spin at your very own Dr. Suess-esque book and use rhymes to tell a kooky, crazy story!',
               'What if we lived in a world where kids were treated like adults? And adults were treated like kids?',
               'Tell the story of your first time away from home.', 'Tell the story of your first time at summer camp.',
               'You and your best friends get to leave school to have lunch anywhere in town. Pizza, candy – anything! Tell the story of where you go.',
               'Describe a trip to the zoo with your class.',
               'If you could taste a specific flavor any time you ate something, what would you want it to be?',
               'If the world could be any color, what would you want it to be?',
               'Your parents tell you one day that you’re going to be a big sister – but you really like being the only child!',
               'Tell the story of a family who decides to hire a new babysitter or nanny.',
               'Write about your favorite childhood game.',
               'Imagine what it would be like to live in a world where instead of taking the school bus, you ride a dragon to classes!',
               'Give advice to your younger self.', 'Give advice to new parents.',
               'Children’s books are known for their fun and creativity. What’s the craziest, kookiest new breed of animal you can imagine?',
               'Dream up your own imaginary world.',
               'Imagine running away with a group of your childhood best friends – where would you go?',
               'Tell the story of a platypus.', 'Tell the story of a child who has just transferred to a new school.',
               'What would happen if you woke up one day and kids ruled the world?',
               'Get inspiration for your writing by thinking about a vacation you took as a child.',
               'Write about your favorite childhood pet.', 'What was your greatest dream when you were a child?',
               'Write about yourself at age ten.', 'Write about yourself at age five.',
               'What parent were you closest do? What are some of your favorite memories of spending time with them?',
               'Write about a special memory from your childhood.',
               'Your parents tell you they’ll give you $20 if you eat your vegetables with every dinner. Do you do it?',
               'You and your boy scout troop get lost in the middle of the forest.',
               'The new kid at school wants to be your friend, but you’re very shy.',
               'Your family adopts a pet monkey.', 'Rain turns into soda.',
               'What would happen if you could turn any food into cotton candy?', 'You turn into a goldfish.',
               'You and your family rescue a turtle who was hit by a car and nurse him back to health.',
               'Dinosaurs come back to earth.', 'Your best friend’s head turns into a mushroom.',
               'The sky turns purple.', 'Your dog begins speaking in a human voice one morning.'],
    'Young Adult': [
        'Your big brother has always been the more successful, studious one of the family. You’ve finally got a chance to prove yourself and one up him – how do you do it?',
        'What would happen if you changed places with a rockstar?',
        'You have the power to shift into whatever creature you want – bear, wolf, etc. When do you choose to utilize your powers?',
        'A small spaceship crash lands in your backyard with nothing inside but an instruction manual on how to rebuild the aircraft. Do you take it back into space?',
        'Think Princess Diaries – you’ve just found out you’re part royal with a massive inheritance to look forward to. What changes about your life?',
        'Tell the story of someone who switches places with themself as a 14-year-old.',
        'What would your younger self tell you now? What would they think about your life?',
        'What would you tell your younger self as a teenager? What do you wish you had done differently, or not done at all?',
        'After going to see the circus with your parents, you decide to run away to join the troupe. What act do you take on?',
        'Some friends go to an escape room only to discover it’s being run by one of the most elusive serial killers in history.',
        'You and your best friends have been playing in a band in your mom’s garage for years. Now you’ve gotten discovered by a major Hollywood scout, but they only want you to go on to fame.',
        'Put yourself in your favorite anime or manga series. What type of character would you play?',
        'Your beloved dog goes missing, resulting in a cross-country chase to reunite her with your family.',
        'You check out a book from the library and discover that it’s telling the story of your life. Do you decide to read ahead and find out what happens, or let it be a surprise?',
        'Soon after a boy was born, his father went missing. Now, a skeleton has been discovered in the basement of their former home. (Bryn Donovan)',
        'A girl struggles with the decision to tell authorities about what the star quarterback did. (Bryn Donovan)',
        'A teen’s suspicions about a teacher lead him to conduct a private investigation. (Bryn Donovan)',
        'A girl’s science fair project yields results that attract the government’s attention. (Bryn Donovan)',
        'A teen gains the ability to take the form of any other person she chooses. (Bryn Donovan)',
        '35. A girl who wants to be a virgin until she gets married faces social pressure about her decision. (Bryn Donovan)',
        'In a modern-day Ferris Bueller’s Day Off, three girls ditch class for a day filled with adventures. (Bryn Donovan)',
        'A boy learns something terrible about his parents.(Bryn Donovan)',
        'A girl always hangs out at a particular little nook at the library. Then the same boy starts taking the space every day. (Bryn Donovan)',
        'In a dystopian future, college admissions boards have access to video footage of students’ entire lives. (Bryn Donovan)',
        'Two teens begin to write a fantasy novel together and then cross over into the world they’ve created. (Bryn Donovan)',
        'A teenager’s best friend goes missing—and is widely believed to be the murderer of a family member. (Bryn Donovan)',
        'A boy learns who believed his sister died finds out she’s very much alive. (Bryn Donovan)',
        'A girl’s favorite author plagiarizes her fanfiction. (Bryn Donovan)',
        'A group of “outsiders” become a clique that eventually excludes others. (Bryn Donovan)',
        'A girl on the swim team transforms into a part-time mermaid. (Bryn Donovan)',
        'A boy pursues his list of wildly ambitious New Year’s resolutions, with hilarious and touching results. (Bryn Donovan)',
        'It was pretty freaky to wake up for school one morning, only to see that my parents were literally frozen into blocks of ice in the kitchen. Even freakier? Every adult in town is frozen solid, too.',
        'One night you wake up to find yourself levitating over your bed. The next morning, strange wings start to grow from your shoulders. Are you turning into some sort of mystical bird?',
        'You did it – after years of hard work and try outs, you finally won the coveted spot on the football team. But here’s the thing – you’re the first girl to ever play.',
        'You find out that your best friend’s dad is responsible for the growing number of missing people in your hometown. How do you get everyone to believe you?',
        'In the near future, climate change has led to the extinction of butterfly and bee pollinators. A small group of teen geniuses band together to develop autonomous, robotic insects to replicate the functions of insect pollination before the global food shortage turns from disastrous to extinction-level.',
        'Imagine that the world is run amok with vampires. Or zombies. Or authoritarian dictatorships in a dystopian future.',
        'Your high school sweetheart dumps you suddenly because of something you posted on social media. But you didn’t post it, and you have to figure out just how different – and difficult – your life is now that you’ve been hacked.',
        'A group of at-risk teenagers are on an overnight camping trip with a wilderness counseling group in Badlands National Park when an arctic blast forces them out of a blizzard and into a cave. On day three, their counselors go out in search for help – and never return.',
        'A group of high school freshmen learn that the teachers and administrators at their boarding school are actually human like AI working towards the Singularity and human enslavement. If they don’t act fast, the robots win.',
        'During her freshman year of college, she found out that people in her dorm started to disappear. Almost from thin air.',
        'You find out that your brother is adopted.',
        'Your boyfriend gets in a horrible car accident and ends up in the ICU. Another girl is found in the car with him, too – but she died. Who is she?',
        'Tell the story of the best high school summer of your life.',
        'Your mom disappears one day, and you never see her again.',
        'You’re chosen to go on a school trip to Africa where you’ll be helping to build wells. You’ve never been out of the country, though, and are worried.',
        'One day you find out that you never have to return to high school. What do you decide to do instead?',
        'Both of your parents die in a car accident, leaving you an orphan who gets shipped off to your mysterious aunt’s house in Europe.',
        'What happens when you begin working at the same yogurt shop as your crush?',
        'It’s your first day of middle school. But when you’re half human, half dragon, that makes things a little tough.']}
